### ISSUE TITLE
Question about ConnectionId

### ISSUE THREAD

**Issue by rgustavsson** [AleksandarTokarev/cordova-plugin-callkit#4]
@AleksandarTokarev 
Do you have any clue if I can get the "ConnectionId" value from the VOIP notification payload when I answer a call? Are you aware of any methods that exposes the ID?

**Comment by AleksandarTokarev** [comment]
The connection ID is a custom field that i am adding myself, it is not something that is created by the VOIP Push Notification @rgustavsson , so pretty much yes you can get that but it would be your custom logic - not related to IOS or Apple

**Comment by rgustavsson** [comment]
Yes so what I am trying to figure out is if I inside the “answer” event (JavaScript) can figure out what the custom events are. Or is your fork totally native?
I imagine that the call screen shouldn’t need to know anything about my WebRTC session, but when I click on answer I would like to connect the user to the session - and the session ID is in a custom property (connection id)

**Comment by AleksandarTokarev** [comment]
On the receive call you get that Connection Id, but not on the answer call as far as i remember. You can fork and modify the plugin if u want to. Basically how we are doing this one is, we have the session (room id) as the ID of the caller, and we have a reactive database which gets the latest database record when you answer, and connects to the room id which is the id of the caller. This can be done in many ways so it is up to you to customize the implementation

**Comment by rgustavsson** [comment]
Thanks for the feedback @AleksandarTokarev

**Comment by rgustavsson** [comment]
@AleksandarTokarev just a side note, do you have "callkit" working in Android with push notifications? Trying to see where to start in terms of push -> trigger call UI, not finding any good tutorials.

**Comment by AleksandarTokarev** [comment]
This fork and plugin work for IOS only, for Android i have forked `phonegap-push-plugin` (which i use for receiving push notifications). Check out this branch which has the changes that work https://github.com/AleksandarTokarev/phonegap-plugin-push/tree/android-native-caller
@rgustavsson

**Comment by rgustavsson** [comment]
@AleksandarTokarev wonderful, thanks!

**Comment by rgustavsson** [comment]
@AleksandarTokarev I already have notifications and I can send data through them which is great. For when the app i closed in the background, have you implemented anything to wake the app up?

**Comment by AleksandarTokarev** [comment]
this is done in the branch above yes

**Comment by rgustavsson** [comment]
@AleksandarTokarev 
Hi! Hope all is well!
How is callkit working our for you nowadays?
I had it working quite well back in september but today I have issues with what I think it callkit interfering with the WebView audio, so the callkit user isn't head by anyone.
Is this anything you've exeperienced?

**Comment by rgustavsson** [comment]
Got my answers - nevermind! :)
